# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pr:
 branches:  # Branch names to include or exclude for triggering a run.
    include: 
    - feature2 
    exclude: 
    - main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
       command: buildAndPush
       Dockerfile: './Dockerfile'
       containerRegistry: sherifsadek
       repository: sherifsadek/pipes
       tags: '$(Build.BuildId)'
