# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
       command: build
       Dockerfile: Dockerfile
       buildContext: .
       containerRegistry: 'Docker Hub'
       repository: 'sherifsadek'
       tags: '$(Build.BuildId)'
