apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: pipes
  labels:
    app: pipes
spec:
  selector:
    matchLabels:
      app: pipes
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: pipes                                 # 6
    spec:
      containers:
        - image: sherifsadek/pipes:latest
          imagePullPolicy: IfNotPresent                         # 7
          name: pipes
          ports:
            - containerPort: 80
