apiVersion: v1
kind: Service              # 1
metadata:
  name: pipes-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 80         # 5
  selector:                # 6
    app: pipes       # 7
